### ISSUE TITLE
unexpected behaviours

### ISSUE THREAD

**Issue by axelmm** [explorigin/starlight-haxe#1]
hi, 

very nice project
1. On FF "Clear completed" didn't worked (visible but don't works as expected).
   It looks like css-ed content doesn't inherit button's handler, hover doesn't work. too.
   After disabling this "css content replacer" (and unhidding original button) it works fine.
2. Bad behaviours: checking (as completed), destroying and editing items doesn't work properly while filtering is active. 
   These event handlers are fired with index value for filtered list ('currentTodos') but operates on full 'todos' array. I think unique 'item.id' should be used. It's probably "ported error" ;)

PS. why not MIT licensing when ... abandoned?
PS2. I couldn't compile it, had to use haxelib dev ..

**Comment by explorigin** [comment]
I'm glad you like what I've done here but this is an abandoned project so I'm not going to fix anything any time soon.  You should look to https://github.com/fponticelli/doom/ instead because it has a community, much better type-safety and the licensing that you desire.

**Comment by axelmm** [comment]
Thx, I've looked at that earlier but had problems with compiling (3.2.1), it looks nicer now (syntax, reducers). Did you tried it (doom) with pouchdb? Or Mithril+Redux / Ithril (haxe) or.you went/going entirely toword js/react/redux and it's ecosystem (reusable components) ??

**Comment by explorigin** [comment]
My interest in Haxe is purely academic.  I liked it because it's write once, compile most places and it's statically typed.  However JS is quickly becoming that so the desire for Haxe is fading.  I took a new job that is using React/Redux and like it quite a lot.
